sudo: required
services:
  - docker

before_install:
  - docker build -t haswinsome/docker-react -f Dockerfile.dev .

script:
  - docker run haswinsome/docker-react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-win"
  env: "DockerWin-env"
  bucket_name: "elasticbeanstalk-us-west-2-451399005291"
  # 跟app name一樣
  bucket_path: "docker-win"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key:
    secure: "$AWS_SECRET_KEY"